language: python
sudo: false

matrix:
  include:
    - python: 3.8.5
      env: DJANGO="==3.1.1"

     - os: osx
      language: generic
      env: DJANGO="==3.1.*"
# Perform the manual steps on OSX to install Python3 and activate venv:
# Since Python versions have been tested on Linux and it is only a matter of
# system architecture, OSX tests will only run on one Python 3 + latest stable
# release for Django.
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 -m venv env        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source env/bin/activate    ; fi

install:
  - pip install -q django$DJANGO