# Generated by Django 3.1.1 on 2020-09-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20200911_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='halaman',
            options={'verbose_name_plural': 'Halaman'},
        ),
    ]
