# Generated by Django 3.1.1 on 2020-09-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20200911_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('isi', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_detil', to='profil.category')),
            ],
            options={
                'verbose_name_plural': 'Halaman',
            },
        ),
        migrations.DeleteModel(
            name='Halaman',
        ),
    ]
