# Generated by Django 3.1.1 on 2020-09-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_auto_20200911_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'ordering': ('ordering',), 'verbose_name_plural': 'Halaman'},
        ),
        migrations.AddField(
            model_name='profil',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
