# Generated by Django 3.1.1 on 2020-09-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_auto_20200911_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Kategori',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='category',
            new_name='kategori',
        ),
    ]
