# Generated by Django 3.1.1 on 2020-09-11 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_auto_20200911_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil_all', to='profil.kategori'),
        ),
    ]
