# Generated by Django 3.1.1 on 2020-09-30 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_auto_20200911_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('isi', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Halaman',
                'ordering': ('ordering',),
            },
        ),
        migrations.RenameModel(
            old_name='Kategori',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
        migrations.AddField(
            model_name='pages',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='profil.category'),
        ),
    ]
