# Generated by Django 3.1.1 on 2020-09-15 18:29

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_auto_20200911_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='isi',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
