# Generated by Django 3.1.1 on 2020-09-30 22:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_auto_20201001_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages',
            name='status',
            field=models.CharField(blank=True, choices=[('Publish', 'Publish'), ('Draft', 'Draft'), ('InActive', 'InActive')], default='Publish', max_length=20),
        ),
        migrations.AlterField(
            model_name='pages',
            name='isi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
