# Generated by Django 3.1.1 on 2020-09-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Kategori_Berita',
        ),
        migrations.RenameField(
            model_name='berita',
            old_name='category',
            new_name='kategori_berita',
        ),
    ]
