# Generated by Django 3.1.1 on 2020-09-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_auto_20200911_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategori_Berita',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='berita',
            old_name='kategori_berita',
            new_name='category',
        ),
    ]
