# Generated by Django 3.1.1 on 2020-09-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_auto_20200911_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_berita', to='berita.category'),
        ),
    ]
