# Generated by Django 3.1.1 on 2020-09-11 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0006_auto_20200911_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'Berita'},
        ),
        migrations.AddField(
            model_name='berita',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
