# Generated by Django 3.1.1 on 2020-09-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0007_auto_20200911_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
