# Generated by Django 3.1.1 on 2020-09-15 18:18

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0009_berita_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='isi',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
