# Generated by Django 3.1.1 on 2020-09-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0010_auto_20200930_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='thumbnail',
            field=models.ImageField(blank=True, default='berita-kosong.png', null=True, upload_to='images'),
        ),
    ]
