# Generated by Django 3.1.1 on 2020-09-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0011_berita_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='thumbnail',
            field=models.ImageField(blank=True, default='berita-kosong.jpg', null=True, upload_to='images'),
        ),
    ]
