# Generated by Django 3.1.1 on 2020-09-30 04:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0013_auto_20200930_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='isi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='berita',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
