# Generated by Django 3.1.1 on 2020-09-30 05:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0014_auto_20200930_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='isi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
