# Generated by Django 3.1.1 on 2020-09-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0015_auto_20200930_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='active',
        ),
        migrations.AddField(
            model_name='berita',
            name='status',
            field=models.CharField(blank=True, choices=[('Publish', 'Publish'), ('Draft', 'Draft'), ('InActive', 'InActive')], default='Publish', max_length=20),
        ),
    ]
