# Generated by Django 3.1.1 on 2020-09-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0016_auto_20200930_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='tags',
            field=models.ManyToManyField(default=1, to='berita.Tag'),
        ),
    ]
