# Generated by Django 3.1.1 on 2020-09-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0018_auto_20201001_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
