# Generated by Django 3.1.1 on 2020-09-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0019_auto_20201001_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
